### PR TITLE
Fix absolute paths

### LINKED ISSUE #35: Absolute paths provided as the source are changed and error out
Hello!

Big fan of the speed gains here, but hit a snag when I was migrating a project away from `fast-glob`. Due to how `tiny-glob` defaults to `.` as the `cwd` if you don't pass anything in, it causes the `path.join` call [within `walk`](https://github.com/terkelg/tiny-glob/blob/master/index.js#L12) to accidentally break the absolute path that was provided as the `src`.

In other words, when I pass in something like:

```
/hello/absolute/path/here/
```

It gets turned into this by that `join` due to that `.` being prepended to the file path:

```
hello/absolute/path/here/
```

Which then throws an error, because that path does not exist.

Not sure how major of a change it'd be, but it may be worth considering hitting a provided source with [`path.isAbsolute`](https://nodejs.org/api/path.html#path_path_isabsolute_path) and skip the `cwd` prepend if it returns `true`?

I didn't check `node-glob`, but it does [appear to be how `fast-glob` approaches this situation](https://github.com/mrmlnc/fast-glob/blob/318b00b6310e0a76d8325a0afb6043ac7a1dc419/src/utils/path.ts#L20-L28).

(Somewhat related, but `fast-glob` also uses [`process.cwd()`](https://nodejs.org/api/process.html#process_process_cwd) instead of defaulting to the string dot `.` for `cwd`, which may also be a bit more resilient to any other weird interpretations of that pathing.)

Happy to take a swing at this as well if you're interested. Thank you!

### PR DESCRIPTION
**Pull request by ForsakenHarmony**
Fixes #35

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -10,15 +10,15 @@ let CACHE = {};
...
+  const dir = resolve(opts.cwd, prefix, dirname);
   const files = await readdir(dir);
   const { dot, filesOnly } = opts;
 
   let i=0, len=files.length, file;
   let fullpath, relpath, stats, isMatch;
 
   for (; i < len; i++) {
-    fullpath = join(dir, file=files[i]);
+    fullpath = resolve(dir, file=files[i]);
```
Comment (lukeed) [inline index.js]: Don't need `resolve` here since `dir` will already be an absolute path. It's more work than is necessary for this point in time :)

```suggestion
    fullpath = join(dir, file=files[i]);
```

Comment (ForsakenHarmony) [reply index.js]: true that

**Comment by ForsakenHarmony** [comment]
welp, this broke some tests

**Comment by terkelg** [comment]
Thank you for the PR @ForsakenHarmony. Sorry I've been busy relocating. Not sure why the tests broke. It's been a while since I've done any work on Tiny Glob

**Comment by ForsakenHarmony** [comment]
Master is actually broken 🙃

guess some update was breaking but not published as breaking

**Comment by ForsakenHarmony** [comment]
it's `globalyzer`, 2 published versions

`0.1.0` works fine
`0.1.4` doesn't, no changelog either @terkelg 👀

**Comment by lukeed** [comment]
Yup! On it now

**Comment by benmccann** [comment]
More info about the test failures here, which are unrelated to this change: https://github.com/terkelg/tiny-glob/pulls#issue-524201732

This PR did have one issue I found though which is that it updated `index.js` and not `sync.js`: https://github.com/terkelg/tiny-glob/pull/57
